version: "3.8"
services:
    app:
        build:
            args:
                user: mateus
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - backend
    db:
        image: oraclelinux:9-slim
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_EXTERNAL_PORT}:3306"
        volumes:
            - ./docker-compose/mysql/:/var/lib/mysql/
        networks:
            - backend

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - backend
    #gitlab:
        #image: gitlab/gitlab-ce:latest
        #container_name: gitlab
        #restart: unless-stopped
        #ports:
        #    - 8080:80
        #    - 8443:443
        #    - 2222:22
        #volumes:
        #    - ./docker-compose/gitlab/config:/etc/gitlab
        #    - ./docker-compose/gitlab/logs:/var/log/gitlab
        #    - ./docker-compose/gitlab/data:/var/opt/gitlab
        #networks:
        #    - backend
    
    #sonarqube:
        #image: sonarqube:latest
        #container_name: sonarqube
        #restart: unless-stopped
        #ports:
        #    - 9001:9000
        #volumes:
        #    - ./docker-compose/sonarqube/conf:/opt/sonarqube/conf
        #    - ./docker-compose/sonarqube/data:/opt/sonarqube/data
        #    - ./docker-compose/sonarqube/logs:/opt/sonarqube/logs
        #    - ./docker-compose/sonarqube/extensions:/opt/sonarqube/extensions

networks:
    backend:
        driver: bridge
        name: backend